_wandb:
    value:
        cli_version: 0.30.0
        e:
            izw48h04wzujve95aptnfcirlac4vryu:
                args:
                    - train
                    - --model
                    - BPR
                    - --config
                    - configs/rec.yaml
                codePath: .venv/bin/recommender
                codePathLocal: .venv/bin/recommender
                email: hangoebl.j@gmail.com
                executable: /home/justin-hangoebl/master-thesis/sid-intent-rec/.venv/bin/python3
                host: sxrk10.cp.jku.at
                os: Linux-6.12.0-211.37.1.el10_2.x86_64-x86_64-with-glibc2.39
                program: /home/justin-hangoebl/master-thesis/sid-intent-rec/.venv/bin/recommender
                python: CPython 3.12.3
                root: /home/justin-hangoebl/master-thesis/sid-intent-rec
                startedAt: "2026-09-19T13:23:37.823730Z"
                writerId: izw48h04wzujve95aptnfcirlac4vryu
        m: []
        python_version: 3.12.3
        t:
            "3":
                - 16
            "4": 3.12.3
            "5": 0.30.0
            "12": 0.30.0
            "13": linux-x86_64
device:
    value: cuda
gpu_id:
    value: 0
num_workers:
    value: 0
out_dir:
    value: runs
seed:
    value: 42
wandb:
    value: true
wandb_project:
    value: Intent Recommender Baselines
wandb_watch:
    value: true
wandb_watch_freq:
    value: 100
wandb_watch_log:
    value: all
